### ISSUE TITLE
Fix the spelling errors in source files

### ISSUE THREAD

**Issue by gboyvalenkov-bosch** [eclipse-kanto/file-upload#3]
Currently, there are many spelling errors in the source files in
- code comments
- functions and variables names
- other

The source files must be examined and all such errors should be fixed.

**Comment by e-grigorov** [comment]
Enable the spell checker and go through all file upload files, there are still some issues:
- client/uploads.go, Stop - fiven should be given
- client/uploads.go, const - redundant comment: // StatePending co and an empty comment right after this one
- client/xtime.go - unmarshall should be unmarshal
- flagparse/flags.go - standart should be standard
- flagparse/flags.go - posible should be possible
- flagparsetest/flags_testutil.go - dupliaction should be duplication
- flagparsetest/flags_testutil.go - neededs should be needs
- logger/logger_test.go - writter should be writer
- uploaders/aws.go - perfroms should be performs
- uploaders/common.go - propery should be property
