### ISSUE TITLE
Feature identifier is configured with "featureID" flag

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/file-upload#46]
The flag and the JSON configuration property must use one and the same name. In this particular case, it's featureId. Currently, `file-upload -h` prints:
```
-featureID string
```
This bug is a result of #7 

Note that the generic configuration processing logic has to be adapted to work with `FeatureID` and `featureId` names. Currently, it's expected to have a difference only in the first letter (see `ToFlagName` and `ToFieldName` methods).

The impact on file backup has to be checked.

**Comment by velitchko-valkov** [comment]
I will take a look at the issue.
