### ISSUE TITLE
Revise/remove dumpFiles configuration property/flag

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/file-upload#9]
This property seems to be more for dev purposes and should be revised/removed. Currently, it does:

> On startup dump the file paths matching the '-files' glob pattern to standard output.

Issues:
* the standard output stream is not used for logging
* the print is just once, the files are collected on each request and the set can be different i.e. there is no real benefit at runtime

I would suggest to remove it.

**Comment by nzhechev-bosch** [comment]
Actually, it is quite useful for sanity checking the glob filter. 

Without this option, it won't be possible to catch errors in the filter during setup, only during runtime, which is much less optimal.

**Comment by e-grigorov** [comment]
Basically, this confirms that it's a dev flag. Glob pattern can be easily checked with different bash commands like "ls". If this initial dump is required, it can be moved as a debug message.

**Comment by e-grigorov** [comment]
Quick synch: @nzhechev-bosch, @e-grigorov, @konstantina-gramatova

Sanity check of the glob filter is just fine but the output will go as a log message with DEBUG level instead of flag/configuration property.

**Comment by daniel-milchev** [comment]
I'll have a look at this.
